set(FILES
    Include/GOAT/GOATTypeIds.h
    Include/GOAT/GOATBackendBus.h
    Include/GOAT/GOATRemoteDebug.h
    Include/GOAT/VocabularyScope.h
    Include/GOAT/Assets/ProgramAsset.h
    Include/GOAT/Assets/BlackboardAsset.h
    Include/GOAT/Domain/ActionPlan.h
    Include/GOAT/Domain/DirectorProfile.h
    Include/GOAT/Domain/PlanStore.h
    Include/GOAT/Domain/ActionState.h
    Include/GOAT/Domain/AgentDebug.h
    Include/GOAT/Domain/AgentId.h
    Include/GOAT/Domain/AgentProgram.h
    Include/GOAT/Domain/AgentStateMachine.h
    Include/GOAT/Domain/BlackboardKey.h
    Include/GOAT/Domain/BlackboardLayout.h
    Include/GOAT/Domain/BlackboardStorage.h
    Include/GOAT/Domain/BlackboardTraits.h
    Include/GOAT/Domain/BlackboardTypes.h
    Include/GOAT/Domain/Handle.h
    Include/GOAT/Domain/Intent.h
    Include/GOAT/Domain/NodeType.h
    Include/GOAT/Domain/PlanContext.h
    Include/GOAT/Interfaces/IActionState.h
    Include/GOAT/Interfaces/IBackend.h
    Include/GOAT/GOATDirectorFilterBus.h
    Include/GOAT/Interfaces/IDirectorFilter.h
    Include/GOAT/Interfaces/IAgentSystem.h
    Include/GOAT/Interfaces/IBlackboardSystem.h
    Include/GOAT/Interfaces/IDecisionBackend.h
    Include/GOAT/Interfaces/INodeScripting.h
    Source/Core/Domain/ActionState.cpp
    Source/Core/Domain/AgentDebug.cpp
    Source/Core/Domain/GOATRemoteDebug.cpp
    Source/Core/Domain/BlackboardKey.cpp
    Source/Core/Domain/BlackboardStorage.cpp
    Source/Core/Domain/BlackboardTypes.cpp
    Source/Core/Domain/Intent.cpp
    Source/Core/Domain/NodeType.cpp
    Source/Core/Domain/PlanStore.cpp
)
