set(FILES
    Source/GOATModuleInterface.cpp
    Source/GOATModuleInterface.h
    Source/Clients/GOATSystemComponent.cpp
    Source/Clients/GOATSystemComponent.h
    Source/Core/Domain/ActionPlan.cpp
    Source/Core/Domain/ActionState.cpp
    Source/Core/Domain/BlackboardKey.cpp
    Source/Core/Domain/BlackboardTypes.cpp
    Source/Core/Domain/Guard.cpp
    Source/Core/Domain/Intent.cpp
    Source/Core/Memory/HandleTable.h
)
