set(FILES
    Source/GOATModuleInterface.cpp
    Source/GOATModuleInterface.h
    Source/Clients/AgentBootstrap.cpp
    Source/Clients/AgentBootstrap.h
    Source/Clients/GOATAgentComponent.cpp
    Source/Clients/GOATDirectorComponent.cpp
    Source/Clients/GOATDirectorComponent.h
    Source/Clients/GOATAgentComponent.h
    Source/Clients/GOATSystemComponent.cpp
    Source/Clients/GOATSystemComponent.h
    Source/Core/Actions/RunScriptAction.cpp
    Source/Core/Actions/RunScriptAction.h
    Source/Core/Actions/WaitAction.cpp
    Source/Core/Actions/WaitAction.h
    Source/Core/Application/ActionStateRegistry.cpp
    Source/Core/Application/ActionStateRegistry.h
    Source/Core/Application/GuardWatch.cpp
    Source/Core/Application/GuardWatch.h
    Source/Core/Application/AgentRecord.h
    Source/Core/Application/AgentArchetype.cpp
    Source/Core/Application/AgentArchetype.h
    Source/Core/Application/AgentRegistry.cpp
    Source/Core/Application/AgentStore.cpp
    Source/Core/Application/AgentStore.h
    Source/Core/Application/AgentRegistry.h
    Source/Core/Application/AgentRuntime.cpp
    Source/Core/Application/AgentRuntime.h
    Source/Core/Application/BackendRegistry.h
    Source/Core/Application/DecisionBackendRegistry.h
    Source/Backends/Htn/HtnBackend.cpp
    Source/Backends/Htn/HtnBackend.h
    Source/Backends/Htn/HtnCompiler.cpp
    Source/Backends/Htn/HtnCompiler.h
    Source/Backends/Htn/HtnDomain.h
    Source/Backends/Htn/HtnPlanner.cpp
    Source/Backends/Htn/HtnPlanner.h
    Source/Backends/BehaviorTree/BehaviorTreeBackend.h
    Source/Backends/BehaviorTree/BehaviorTreeWords.cpp
    Source/Backends/BehaviorTree/BehaviorTreeWords.h
    Source/Backends/BehaviorTree/BehaviorTreeBackend.cpp
    Source/Backends/BehaviorTree/DecisionCursor.h
    Source/Backends/BehaviorTree/DecisionCursor.cpp
    Source/Backends/BehaviorTree/GuardEvaluator.h
    Source/Backends/BehaviorTree/GuardEvaluator.cpp
    Source/Backends/BehaviorTree/NodePredicate.h
    Source/Backends/BehaviorTree/NodePredicate.cpp
    Source/Backends/BehaviorTree/ServiceTracker.h
    Source/Backends/BehaviorTree/ServiceTracker.cpp
    Source/Backends/BehaviorTree/TreeCompiler.h
    Source/Backends/BehaviorTree/TreeCompiler.cpp
    Source/Backends/BehaviorTree/TreeWalker.h
    Source/Backends/BehaviorTree/TreeWalker.cpp
    Source/Core/Application/NamedRegistry.h
    Source/Core/Application/NodeTypeRegistry.cpp
    Source/Core/Application/NodeTypeRegistry.h
    Source/Core/Application/ReachFilterRegistry.h
    Source/Core/Director/DirectorActions.cpp
    Source/Core/Director/DirectorActions.h
    Source/Core/Director/DirectorKeys.cpp
    Source/Core/Director/DirectorKeys.h
    Source/Core/Director/DirectorRegistry.cpp
    Source/Core/Director/DirectorRegistry.h
    Source/Core/Application/BlackboardSystem.cpp
    Source/Core/Application/BlackboardSystem.h
    Source/Core/Application/SquadRegistry.cpp
    Source/Core/Application/SquadRegistry.h
    Source/Core/Assets/BehaviorTreeAsset.cpp
    Source/Core/Assets/BlackboardAsset.cpp
    Source/Core/Assets/BlackboardAssetHandler.cpp
    Source/Core/Assets/BlackboardAssetHandler.h
    Source/Core/Domain/PlanStore.cpp
    Source/Core/Domain/ActionState.cpp
    Source/Core/Domain/AgentStateMachine.cpp
    Source/Core/Domain/BlackboardKey.cpp
    Source/Core/Domain/BlackboardSchema.cpp
    Source/Core/Domain/BlackboardSchema.h
    Source/Core/Domain/BlackboardStorage.cpp
    Source/Core/Domain/BlackboardTypes.cpp
    Source/Core/Domain/Guard.cpp
    Source/Core/Domain/Intent.cpp
    Source/Core/Domain/NodeType.cpp
    Source/Core/Frontend/TreeLibrary.cpp
    Source/Core/Frontend/TreeLibrary.h
    Source/Core/Scripting/AgentScriptContext.cpp
    Source/Core/Scripting/AgentScriptContext.h
    Source/Core/Scripting/LuaBackend.cpp
    Source/Core/Scripting/LuaBackend.h
    Source/Core/Scripting/LuaDispatch.cpp
    Source/Core/Scripting/LuaDispatch.h
    Source/Core/Scripting/LuaNameCollector.cpp
    Source/Core/Scripting/LuaNameCollector.h
    Source/Core/Scripting/LuaNodeScripting.cpp
    Source/Core/Scripting/LuaNodeScripting.h
    Source/Core/Scripting/LuaPlanBuilder.cpp
    Source/Core/Scripting/LuaPlanBuilder.h
    Source/Core/Scripting/LuaPlanValidator.cpp
    Source/Core/Scripting/LuaPlanValidator.h
    Source/Core/Scripting/LuaTreeBuilder.cpp
    Source/Core/Scripting/LuaTreeBuilder.h
)
