set(FILES
    Include/GOAT/GOATBus.h
    Include/GOAT/GOATTypeIds.h
    Include/GOAT/Domain/ActionPlan.h
    Include/GOAT/Domain/ActionState.h
    Include/GOAT/Domain/BlackboardKey.h
    Include/GOAT/Domain/BlackboardTypes.h
    Include/GOAT/Domain/Guard.h
    Include/GOAT/Domain/Handle.h
    Include/GOAT/Domain/Intent.h
)
